application: voc4u9
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /styles
  static_dir: content/styles

- url: /js
  static_dir: content/js

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: helloworld.py
  
  

  
